[package]
name = "texture"
authors = ["Chinedu Francis Nwafili"]
version = "0.0.1"
publish = false
edition = "2018"

[build-dependencies]
bindgen = "0.53.2"

[dependencies]
cocoa = "0.23"
core-graphics = "0.22"
png = "0.16"
metal = { path = "../../" }
winit = "0.22"

[dependencies.objc]
version = "0.2.4"
features = ["objc_exception"]
